platform :ios, '10.0'
use_frameworks!

target 'SBLibrary_Example' do
  pod 'SBLibraryV2', :path => '../'
  #pod 'SBLibraryV2' , :git => 'https://github.com/GameStar4Kid/SBLibraryV2.git'
  target 'SBLibrary_Tests' do
    inherit! :search_paths
  end
end
