use_frameworks!

target 'SBLibrary_Example' do
  pod 'SBLibraryV2' , :git => 'https://github.com/GameStar4Kid/SBLibraryV2.git'

  target 'SBLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
